require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")
spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.cmp")
spec("user.telescope")
spec("user.none-ls")
spec("user.illuminate")
spec("user.gitsigns")
spec("user.whichkey")
spec("user.nvimtree")
spec("user.comment")
spec("user.lualine")
spec("user.navic")
spec("user.breadcrumbs")
spec("user.harpoon")
-- spec "user.neotest"
spec("user.autopairs")
spec("user.neogit")
spec("user.alpha")
spec("user.project")
spec("user.indentline")
spec("user.toggleterm")
spec("user.neodev")
spec("user.dap")
spec("user.bufdelete")
-- Extras
spec("user.extras.colorizer")
spec("user.extras.obsidian")
spec("user.extras.pomo")
-- spec("user.extras.neoscroll")
spec("user.extras.copilot")
spec("user.extras.modicator")
spec("user.extras.rainbow")
spec("user.extras.zen")
-- spec "user.extras.bqf"
-- spec "user.extras.dial"
spec("user.extras.dressing")
spec("user.extras.eyeliner")
spec("user.extras.navbuddy")
spec("user.extras.oil")
spec("user.extras.fidget")
spec("user.extras.neotab")
spec("user.extras.lab")
spec("user.extras.tabby")
spec("user.extras.tsc")
spec("user.extras.gitlinker")
spec("user.extras.todo-comments")
spec("user.extras.cellular-automaton")
require("user.lazy")
